on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - "*.md"
      - ".github/**"
      - "template/**"

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build image"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Generate date-based tag
        id: date_tag
        run: echo "DATE_TAG=$(TZ='Asia/Shanghai' date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push images to Docker hub
        uses: docker/build-push-action@v5.1.0
        with:
          # (推荐) 指定 Dockerfile 所在的目录
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:latest
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.DATE_TAG }}
